name: GUI test

on:
  workflow_call:
    inputs:
      python-version:
        default: 3.8
        type: string
        required: false

      matrix:
        default: '{"os":["windows-latest"]}'
        type: string
        required: false

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(inputs.matrix)}}

    steps:
      - uses: actions/checkout@v3

      - name: Create python environment
        uses: ./.github/actions/pyenv
        with:
          python-version: ${{inputs.python-version}}
          requirements: requirements-test.txt

      - name: Install dependencies (Win)
        if: runner.os == 'Windows'
        uses: ./.github/actions/windows_dependencies

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt install pyqt5-dev-tools

      - name: Setup headless display
        if: runner.os == 'Linux'
        uses: pyvista/setup-headless-display-action@v1

      - name: Run GUI tests
        timeout-minutes: 5
        run: |
          pytest ./src/tribler/gui --guitests -v --randomly-seed=1 --timeout=300

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{runner.os}}_screenshots
          path: ./src/tribler/gui/screenshots/
          retention-days: 1
