name: Pytest

on:
  workflow_call:
    inputs:
      python-version:
        default: 3.8
        type: string
        required: false

      matrix:
        default: '{"os":["ubuntu-latest"]}'
        type: string
        required: false

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(inputs.matrix)}}

    steps:
      - uses: actions/checkout@v3

      - name: Create python environment
        uses: ./.github/actions/pyenv
        with:
          python-version: ${{inputs.python-version}}
          requirements: requirements-test.txt

      - name: Install windows dependencies
        if: runner.os == 'Windows'
        uses: ./.github/actions/windows_dependencies

      - name: Run Pytest (nix)
        if: runner.os != 'Windows'
        timeout-minutes: 5
        run: |
          pytest ./src/tribler/core --exitfirst --disable-warnings --looptime

      - name: Run Pytest (win)
        if: runner.os == 'Windows'
        timeout-minutes: 5
        run: |
          pytest ./src/tribler/core --exitfirst --disable-warnings
          
      - name: Run Tunnels Tests
        run: |
          pytest ./src/tribler/core/components/tunnel/tests/test_full_session --tunneltests --exitfirst --disable-warnings
